# Generated by Django 2.2 on 2020-01-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200118_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
